### ISSUE TITLE
nit: PEM keys can be parsed via github.com/lestrrat-go/jwx

### ISSUE THREAD

**Issue by lestrrat** [serg-kovalev/rsa2jwk#10]
https://github.com/serg-kovalev/rsa2jwk/blob/9d49915e49e8e4e53bf56a4073d716b7db87f701/rsa2jwk.go#L119

This can be done like this:

```go
jwkSet, err := jwk.Parse(byteSequence, jwk.WithPEM(true))
```

Or even, read it straight out of a file:

```go
jwkSet, err := jwk.ReadFile(path, jwk.WithPEM(true))
```

Additionally, if you know that there's exactly one key in the source, you could also do

```go
key, err := jwk.ParseKey(byteSequence, jwk.WithPEM(true))
```

**Comment by serg-kovalev** [comment]
@lestrrat this is really handy! Thank you for letting me know about that!
Huge thanks for making those packages and for your contributions :)
